.TH server 1 "November 28, 2020" 
.SH NAME
server \- Run a server program that will listen to messages on a port and perform "work" sent by a client.
.SH SYNOPSIS
\fBserver\fP \fIport_number\fP 
.SH DESCRIPTION
.TP
\fBserver\fP run a server program on designated \fIport_number\fP 
.TP
\fBport_number\fP the port the server is listening for messages, must be in range 5,000 - 64,000.

.SH REQUIRED FILES 
.TP
\fCMakefile\fR
makefile to compile server program
.TP
\fC/src/server/main.cpp\fR
driver code that will initiate the server program 
.TP
\fC/src/server/server.cpp\fR
source code for server program 
.TP
\fC/src/logger.cpp\fR
logger class to create and write to a log file
.TP
\fC/src/tands.cpp\fR
helper file to simulate doing work
.TP
\fC/src/helper.cpp\fR
helper file that holds helper functions
.TP
\fC/include/\fR
directory holding header files
